### PR TITLE
Fix Redis <=6.2 throwing errors when trying to clear the command queue in pooling mode.

### LINKED ISSUE #1761: Failed to trim commands from the IN/OUT stream ReplyError: ERR syntax error
```
WARN 09:58:51:848 [IrcConnectionPool] Failed to trim commands from the IN stream ReplyError: ERR syntax error
...
     args: [ 'ircbridge.stream.command.in', 'MINID', '1690797483729-0' ]
```

Looks like we're failing to specify the min ID without the suffix, upsetting the TRIM syntax.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #1761 

Ultimately the problem here is that we failed to specify a minimum Redis version. If you are using less than 6.2, you won't be able to clear the command stream effectively. To get around this for now, we're reverting to previous behaviour of just setting an absolute maximum message count for the stream when running on older Redis versions.

### CODE REVIEW

File: src/pool-service/CommandReader.ts [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+                    .catch(ex => log.warn(`Failed to handle msg ${msgId} (${cmdType}, ${payload})`, ex)
+                    ),
+            );
+        }
+
+    }
+
+    public async getSupported() {
+        const serverLines = (await
+        this.redis.info("Server")).split('\n').filter(v => !v.startsWith('#')).map(v => v.split(':', 2)
```
Comment (tadzik) [inline src/pool-service/CommandReader.ts]: Ouch. Awkward that there's no easier way to do this.

File: src/pool-service/CommandReader.ts [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+        ) as [string, string][];
+        const options = new Map(serverLines);
+        const version = options.get('redis_version');
+        if (!version) {
+            log.warn(`Unable to identify Redis version, assuming unsupported version`);
```
Comment (tadzik) [inline src/pool-service/CommandReader.ts]: Perhaps we should also do this if parsing the server info failed for any reason.

**Review by tadzik — CHANGES_REQUESTED** [review]
Some concerns. I like the refactoring!

File: src/pool-service/CommandReader.ts (hunk 1 above)
Comment (Half-Shot) [reply src/pool-service/CommandReader.ts]: I was quite annoyed the library didn't parse this for us, but oh well.

**Review by tadzik — APPROVED** [review]
