### PR TITLE
Upgrade dependencies to fix room visibility bug (requires Node 16)

### LINKED ISSUE #1606: Room visibility setting is broken for appservice directories
The bridge is trying to set the visibility of a room to its network name -_-

```
122022-09-13 08:42:28 INFO:IrcBridge [-] PUT http://localhost:8008/_matrix/client/r0/directory/list/appservice/!ulpzbqqkOSdqWjdtrb%3Abeefy/public (AS) Body: "{\"visibility\":\"localhost\"}"
```

### PR DESCRIPTION
**Pull request by jaller94**
* Fixes `RoomConfig.getRoomState()` returning `Promise<undefined>` instead of `Promise<null>` on timeouts. This violated the function's type signature.
* Fixes #1606
* **Breaking change**: Raises the required NodeJS version to 16.

### CODE REVIEW

File: changelog.d/1616.bugfix [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Breaking change: Raises the required NodeJS version to 16.
```
Comment (Half-Shot) [inline changelog.d/1616.bugfix:1]: This should probably be a `.removal`, as it gets it's own heading.

File: changelog.d/1616.bugfix [hunk 2]
```diff
@@ -0,0 +1,4 @@
...
+Fixes RoomConfig.getRoomState() returning Promise<undefined> instead of Promise<null> on timeouts. This violated the function's type signature.
```
Comment (Half-Shot) [inline changelog.d/1616.bugfix:2]: I wouldn't bother listing internal changes here, unless it affects the admins of the bridge in a way they can understand.

File: package.json [hunk 3]
```diff
@@ -28,43 +28,43 @@
...
-    "diff": "^5.0.0",
+    "diff": "^5.1.0",
     "escape-string-regexp": "^4.0.0",
     "extend": "^3.0.2",
     "he": "^1.2.0",
-    "logform": "^2.4.0",
-    "matrix-appservice-bridge": "^3.2.0",
+    "logform": "^2.4.2",
+    "matrix-appservice-bridge": "^5.1.0",
     "matrix-org-irc": "1.3.0",
```
Comment (Half-Shot) [inline package.json:37]: Could this be bumped to 1.4.0 :)

**Review by Half-Shot — CHANGES_REQUESTED** [review]
Couple of things
