### PR TITLE
Fix registration bug

### LINKED ISSUE #872: Error when generating registration file
I have tested this both inside a snap package, and outside on my workstation using plain old npm & node to install, and I get the same behaviour - both with my config file for my homeserver, and the default sample configuration file in the matrix-appservice-irc repository.

Node version on my workstation: v10.15.2 (used when building and running without snap)
Node version inside snap: v12.13.0 (used when building the snap and testing inside the snap) 

I'm not able to generate a registration file, the following error is produced using the commandline provided in the README.md.

```
ubuntu@juju-235d78-0:/snap/matrix-appservice-irc/current$ node app.js -r -f /var/snap/matrix-appservice-irc/common/registration.yaml -u "http://localhost:9999" -c /var/snap/matrix-appservice-irc/common/config.yaml -l ircbridge
/snap/matrix-appservice-irc/x4/app.js:40
        main.generateRegistration(reg, this.getConfig()).done(function(completeRegistration) {
                                                         ^

TypeError: main.generateRegistration(...).done is not a function
    at Cli.generateRegistration (/snap/matrix-appservice-irc/x4/app.js:40:58)
    at Cli._generateRegistration (/snap/matrix-appservice-irc/x4/node_modules/matrix-appservice-bridge/lib/components/cli.js:172:46)
    at Cli.run (/snap/matrix-appservice-irc/x4/node_modules/matrix-appservice-bridge/lib/components/cli.js:118:14)
    at Object.<anonymous> (/snap/matrix-appservice-irc/x4/app.js:53:4)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

### PR DESCRIPTION
**Pull request by Half-Shot**
Should fix #872 

Promise.done is no longer a thing (we are phasing out Bluebird), use `async/await`

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -36,10 +36,15 @@ new Cli({
             }
         }
     },
-    generateRegistration: function(reg, callback) {
-        main.generateRegistration(reg, this.getConfig()).done(function(completeRegistration) {
-            callback(completeRegistration);
-        });
+    generateRegistration: async function(reg, callback) {
```
Comment (benparsons) [inline app.js]: this doesn't need to be async?
