### PR TITLE
Enure CTCP from address is valid

### LINKED ISSUE #1051: Failure on startup
I am trying to setup a new irc bridge and while it starts and connects to the irc side it seems like a thread or something else is failing. The end result is the IRC side stays up and seemingly responsive as it doesn't ping out and the irc bot responds to PMs but it looks like maybe the Matrix side is what crashed?

```
2020-05-12 03:26:00 INFO:BridgedClient <MatrixBot@sonikku.afternet.org#j602f9lqtns00> Connecting to IRC server sonikku.afternet.org as MatrixBot (user=matrixirc)
2020-05-12 03:26:01 DEBUG:client-connection Received ping from 455966613 directed at MatrixBot
FATAL EXCEPTION
TypeError: Cannot read property 'length' of undefined
    at Client._splitMessage (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1147:58)
    at Client._speak (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1161:30)
    at Client.notice (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1142:17)
    at Client.ctcp (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1265:55)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/lib/irc/ConnectionInstance.js:276:25)
    at Client.emit (events.js:310:20)
    at Client.EventEmitter.emit (domain.js:482:12)
    at Client._handleCTCP (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1257:14)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:612:26)
    at Client.emit (events.js:322:22)
    at Client.EventEmitter.emit (domain.js:482:12)
    at iterator (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:934:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:929:15)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
2020-05-12 03:26:06 ERROR:main FATAL EXCEPTION
2020-05-12 03:26:06 ERROR:main TypeError: Cannot read property 'length' of undefined
    at Client._splitMessage (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1147:58)
    at Client._speak (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1161:30)
    at Client.notice (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1142:17)
    at Client.ctcp (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1265:55)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/lib/irc/ConnectionInstance.js:276:25)
    at Client.emit (events.js:310:20)
    at Client.EventEmitter.emit (domain.js:482:12)
    at Client._handleCTCP (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1257:14)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:612:26)
    at Client.emit (events.js:322:22)
    at Client.EventEmitter.emit (domain.js:482:12)
    at iterator (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:934:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:929:15)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
2020-05-12 03:26:06 ERROR:main Terminating (exitcode=1)
2020-05-12 03:26:06 INFO:PgDatastore Fetching all channels for sonikku.afternet.org
2020-05-12 03:26:06 INFO:IrcBridge Startup complete.
```

Not sure of exact steps to reproduce other than config and start.

Version: 0.17.1
Ircd: NefariousIRCu u2.10.12.14+Nefarious(2.0.0)+[2.0-228-ged12d64]

I do have 0.17.0 running on another network using the same ircd (u2.10.12.14+Nefarious(2.0.0)+[2.0-223-ged6b679]) which is showing no issues.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #1051

### CODE REVIEW

File: src/irc/ConnectionInstance.ts [hunk 1]
```diff
@@ -330,7 +330,9 @@ export class ConnectionInstance {
 
     private listenForCTCPVersions() {
         this.client.addListener("ctcp-version", (from: string) => {
```
Comment (jaller94) [inline src/irc/ConnectionInstance.ts:332]: If string can be falsey, this signature is incorrect.

Comment (jaller94) [reply src/irc/ConnectionInstance.ts:332]: Not changing the signature?
This `from: string` should likely be `from: string|undefined` or ``from: string|null`.
