### PR TITLE
Handle replies that contain displaynames

### LINKED ISSUE #915: Messages with `m.in_reply_to` are not propagating to IRC
Stumbled upon this bug while investigating why Telegram-to-Telegram replies (generated by mautrix-telegram appservice) are not propagated to IRC ([see bug report](https://github.com/tulir/mautrix-telegram/issues/400)).

To reproduce, send the following minimal message from Matrix:

```
{
    "body": "testing",
    "msgtype": "m.text",
    "m.relates_to": {
	"event_id": "$15760700702709kXicd:hacklab.fi",
	"rel_type": "m.reference",
	"m.in_reply_to": {
            "event_id": "$15760700702709kXicd:hacklab.fi"
	}
    }
}
```

And then remove `m.in_reply_to` object and resend the message. The message is then propagating to IRC.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #915

### CODE REVIEW

File: src/bridge/MatrixHandler.ts [hunk 1]
```diff
@@ -1097,7 +1097,7 @@ export class MatrixHandler {
 
     private async textForReplyEvent(event: MatrixMessageEvent, replyEventId: string, ircRoom: IrcRoom):
     Promise<{formatted: string; reply: string}|null> {
-        const REPLY_REGEX = /> <(@.*:.*)>(.*)\n\n(.*)/;
+        const REPLY_REGEX = /> <(.*)>(.*)\n\n(.*)/;
```
Comment (14mRh4X0r) [inline src/bridge/MatrixHandler.ts]: Might want to change this to:

```js
const REPLY_REGEX = /> <(.*?)>(.*?)\n\n(.*)/;
```

These [non-greedy matches](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers) make sure that in e.g.

```
<SomeName> if x > 2

Some reply that could, technically

Contain >2 newlines

Or even more
```

the first group will match `SomeName` instead of `SomeName> if x`, or, in this case,

```
SomeName> if x > 2

Some reply that could, technically,

Contain 
```

And the second group `if x > 2` instead of `  2` or, in this case, `2 newlines`,
and the third group 

```
Some reply that could, technically

Contain >2 newlines

Or even more
```

instead of 

```
Contain >2 newlines

Or even more
```

or, in this case,

```
Or even more
```

Comment (14mRh4X0r) [reply src/bridge/MatrixHandler.ts]: I just realized that this *would* break on display names with `>` in them. To rule this out, I guess you'd need to parse the HTML.
