### PR TITLE
Fix nickname validation bug

### LINKED ISSUE #1313: !irc nick fails when no argument is provided
Instead of saying that the argument is missing, it shows this error
> Unable to change nick: Cannot read property 'replace' of undefined

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #1313

### CODE REVIEW

File: src/bridge/MatrixHandler.ts [hunk 1]
```diff
@@ -811,12 +811,20 @@ export class MatrixHandler {
         const [targetRoom] = await this.ircBridge.getStore().getIrcChannelsForRoomId(event.room_id);
         if (command === "nick") {
             const newNick = args[0];
+            if (newNick?.length > 0) {
```
Comment (jaller94) [inline src/bridge/MatrixHandler.ts:814]: I think this does the opposite of what it should do, rejecting all newNicks with a length greater 0.
```suggestion
            if (!(newNick?.length > 0)) {
```

**Review by jaller94 — CHANGES_REQUESTED** [review]

File: src/bridge/MatrixHandler.ts (hunk 1 above)
Comment (Half-Shot) [reply src/bridge/MatrixHandler.ts:814]: Doh!

**Review by jaller94 — APPROVED** [review]
Looks good to me.
