### PR TITLE
Store room visibility cache in the DB

### LINKED ISSUE #880: We should cache directory PUTs
Rather than PUTing all the rooms on startup each time, the database should keep track of it's state locally and only make the call if the room's status has changed. Currently, we absolutely hammer the homeserver on startup and most of the requests fail anyway.

### PR DESCRIPTION
**Pull request by Half-Shot**
Soft dependency on #881 

Fixes #880 

This is a simple change which caches the room directory visibility in the database rather than just in memory, so that restarts do not spam the homeserver with requests.

### CODE REVIEW

File: src/bridge/PublicitySyncer.ts [hunk 1]
```diff
@@ -202,25 +202,25 @@ export class PublicitySyncer {
         const cli = this.ircBridge.getAppServiceBridge().getBot().getClient();
 
         // Update rooms to correct visibilities
-        const promises = roomIds.map((roomId) => {
-            const currentState = this.visibilityMap.roomVisibilities[roomId];
+        const promises = roomIds.map(async (roomId) => {
+            const currentState = await this.ircBridge.getStore().getRoomVisibility(roomId);
```
Comment (benparsons) [inline src/bridge/PublicitySyncer.ts]: Possible perf issue - what is the expected size of `roomIds` here? Could end up making loads of tiny `select`s when you could group them together then iterate.
