### PR TITLE
Make sure message diffs are not longer than the new message would be

### LINKED ISSUE #1477: New message edit logic makes some edits more verbose than before
**Describe the bug**
When a message like this:

```
Lorem ipsu dolor sit - an arbitrary amount of trailing text will be duplicated in the sed expression, even though it should only include a few words of context
```

is edited to this:

```
Lorem ipsum dolor sit amet - an arbitrary amount of trailing text will be duplicated in the sed expression, even though it should only include a few words of context
```

The following message is posted to IRC:

```
s/Lorem ipsu dolor sit - an arbitrary amount of trailing text will be duplicated in the sed expression, even though it should only include a few words of context/Lorem ipsum dolor sit amet - an arbitrary amount of trailing text will be duplicated in the sed expression, even though it should only include a few words of context/
```

This is much longer than what would have been produced before #1465.

**To Reproduce**
1. Post the first message above to an IRC-bridged matrix room.
2. Edit the message to resemble the second message above
3. Observe the overly long edit message in IRC

**Expected behavior**
A shorter edit summary should be produced - maybe something like `* Lorem ipsum dolor sit amet - an arbitrary`.

Note: this was observed in a libera.chat room.

### PR DESCRIPTION
**Pull request by tadzik**
Partially fixes #1477 – better diff detection would be better eventually, but this at least reduces the annoyance now

### CODE REVIEW

**Review by Half-Shot — APPROVED** [review]
Seems sensible to me :+1:

File: changelog.d/1477.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Make sure message diffs are not longer than the new message would be
```
Comment (Half-Shot) [inline changelog.d/1477.bugfix:1]: Oh, could we explain this a bit more? "Matrix message edits no longer bridge as a diff if it's longer than the new message"

Comment (tadzik) [reply changelog.d/1477.bugfix]: I like it. Changed in 1c526cb7
